### ISSUE TITLE
User & password to open DB files?

### ISSUE THREAD

**Issue by dsomar** [soliantconsulting/carafe#4]
I can't find any mention of the username & password in documentation

**Comment by S11Kelevra** [comment]
Should be admin admin

**Comment by jeremiahsmall** [comment]
Yes, it's prominently displayed when you open Carafe.fmp12, but I'll also add it to the README.md in case people open Carafe Examples.fmp12 first.

**Comment by jeremiahsmall** [comment]
Resolved in 0.4.0
